### ISSUE TITLE
Shut Down

### ISSUE THREAD

**Issue by Irishking03** [m0ranwad/nba-led-scoreboard#8]
Just an fyi I run the NBA board or NFL and after a period of time the board shuts down/Off.. Any ideas @alexanderthebadatcoding

**Comment by alexanderthebadatcoding** [comment]
@Irishking03 try something like this: https://www.piawesome.com/how-tos/Supervisor%20as%20a%20Background%20Service%20Manager.html

**Comment by m0ranwad** [comment]
I run it as a Service in Supervisor, as well. I'll probably include a writeup in the Readme at some point.

**Comment by alexanderthebadatcoding** [comment]
I also have some other example code you can run, https://github.com/alexanderthebadatcoding/LED-python-code/tree/main/samples 
just some simple examples like a clock script or show the price of bitcoin etc. just edit the samplebase.py file.
I just keep them in the nfl scoreboard samples folder(matrix/bindings/python/samples) and run them from there.

**Comment by Irishking03** [comment]
@alexanderthebadatcoding hey you know what I also noticed on the NFL board.. Last night around 10pm (Saturday) it displayed all of Sundays games at 1pm 4pm etc but it didnt have the date for Sunday it said today. As if the time was future dated.. Where or how can I fix that one.

**Comment by alexanderthebadatcoding** [comment]
@Irishking03 I noticed that too, you have to change it from UTC time zone to the device specific. Line 34 in the data/data.py file, change it from:

```   
     def get_current_date(self):
        return datetime.utcnow()
```       
to 
```
    def get_current_date(self):
        return datetime.now()
```

**Comment by Irishking03** [comment]
@alexanderthebadatcoding FYI this is what it says right before board shuts off. Now its shutting off literally 10 minute's into it. Frustration sets in.

 INFO (19:20:56): ping render_game
INFO (19:21:02): Live State, checking every 5s
home:  17 away:  17
INFO (19:21:02): ping render_game
Error encountered getting game info, can't hit ESPN api, retrying
Traceback (most recent call last):
  File "/home/fartgoat/nfl-led-scoreboard/main.py", line 30, in <module>
    MainRenderer(matrix, data).render()
  File "/home/fartgoat/nfl-led-scoreboard/renderer/main.py", line 32, in render
    self.__render_game()
  File "/home/fartgoat/nfl-led-scoreboard/renderer/main.py", line 41, in __render_game
    self.__draw_game(self.data.current_game())
  File "/home/fartgoat/nfl-led-scoreboard/data/data.py", line 79, in current_game
    return self.games[self.current_game_index]
TypeError: 'NoneType' object is not subscriptable

**Comment by m0ranwad** [comment]
> @alexanderthebadatcoding FYI this is what it says right before board shuts off. Now its shutting off literally 10 minute's into it. Frustration sets in.
> 
> INFO (19:20:56): ping render_game INFO (19:21:02): Live State, checking every 5s home: 17 away: 17 INFO (19:21:02): ping render_game Error encountered getting game info, can't hit ESPN api, retrying Traceback (most recent call last): File "/home/fartgoat/nfl-led-scoreboard/main.py", line 30, in MainRenderer(matrix, data).render() File "/home/fartgoat/nfl-led-scoreboard/renderer/main.py", line 32, in render self.__render_game() File "/home/fartgoat/nfl-led-scoreboard/renderer/main.py", line 41, in __render_game self.__draw_game(self.data.current_game()) File "/home/fartgoat/nfl-led-scoreboard/data/data.py", line 79, in current_game return self.games[self.current_game_index] TypeError: 'NoneType' object is not subscriptable

Do you mind sharing the Stack Trace for the NBA Board for this repo?

**Comment by Irishking03** [comment]
Sure what exactly do you need me to copy.

**Comment by alexanderthebadatcoding** [comment]
I think it's an issue with the ESPN api. It can happen for either the NBA or NFL. I think ESPN is updating it or it's just down temporarily.

I wonder of there's a way to do the error handling so it restarts or skips if there's an error. I'm going to tinker with it.
